name: Cypress E2E

on: [deployment_status]

jobs:
  cypress-install:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.6.0-chrome105-ff104
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache NPM and Cypress
        id: cache-npm-and-cypress
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/Cypress
            node_modules
            ~/.npm
          key: my-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Cypress install
        if: ${{ steps.cache-npm-and-cypress.output.cache-hit != 'true' }}
        uses: cypress-io/github-action@v4
        with:
          runTests: false

  cypress-run:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.6.0-chrome105-ff104
      options: --user 1001
    needs: cypress-install
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache NPM
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.npm
          key: my-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: UI Tests - Chrome
        uses: cypress-io/github-action@v4
        with:
          install: ${{ steps.cache-npm.output.cache-hit != 'true' }}
          headed: true
          browser: chrome
          record: true
          parallel: true
          group: "UI - Chrome"
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TZ: Asia/Hong_Kong
