name: Cypress E2E

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:latest
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          runTests: false
          build: npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: |
            .next/
            public/

  cypress:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:latest
      options: --user 1001
    needs: install
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build

      - run: ls -al

      - name: UI Tests - Chrome
        uses: cypress-io/github-action@v4
        with:
          install: false
          start: npm run start
          wait-on: "http://localhost:3000"
          browser: chrome
          record: true
          parallel: true
          group: "UI - Chrome"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
